Make Py3 compatible and disable analytics by default.
mrbeam/MrBeamLedStrips pull request #22
Opened 2021-02-27 00:49 UTC by amrsoll

I mainly disabled analytics by default to debug easily.

2021-02-27 00:57 UTC, amrsoll commented
Also I'm currently using this for BeamOS

2021-03-08 14:29 UTC, Gallore requested changes
Please do not disable analytics! How would it get enabled?
If the user did not agree to analytics no analytics data get written nor uploaded by our plugin. But in this case it's required that the analytics data are sent to the plugin in any case.

2021-03-26 13:07 UTC, Gallore requested changes
make it work without config file and enable analytics

2021-03-31 20:47 UTC, amrsoll commented
TODO : create if branches / try catch to differentiate between py2 and py3, because the neopixel lib and functions have changed.
See 5d4acbd

2021-04-08 16:14 UTC, Gallore commented on mrbeam_ledstrips/client.py
> +		# s.sendall(b'info')
please check

2021-04-08 16:22 UTC, Gallore approved these changes
please look at the comment

2021-04-12 08:51 UTC, merged